# Generated by Django 6.1.1 on 2026-10-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opis_id",
                    models.IntegerField(
                        db_index=True, verbose_name="OPIS Truckstop ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Truckstop Name"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=10)),
                (
                    "rack_id",
                    models.IntegerField(blank=True, null=True, verbose_name="Rack ID"),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=4,
                        max_digits=7,
                        verbose_name="Retail Price ($/gal)",
                    ),
                ),
                ("latitude", models.FloatField(db_index=True)),
                ("longitude", models.FloatField(db_index=True)),
            ],
            options={
                "verbose_name": "Fuel Station",
                "verbose_name_plural": "Fuel Stations",
                "ordering": ["retail_price"],
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"], name="idx_fuelstation_lat_lon"
                    ),
                    models.Index(
                        fields=["state", "city"], name="idx_fuelstation_state_city"
                    ),
                    models.Index(fields=["retail_price"], name="idx_fuelstation_price"),
                ],
            },
        ),
    ]
